import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Amplify } from "aws-amplify"; // Import Amplify
import outputs from "../amplify_outputs.json"; // Import the config generated by the sandbox
import "./index.css";
import App from "./App.jsx";

// Configure Amplify with the generated outputs
Amplify.configure(outputs);

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>
);
